#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

# check if we need to download input.tar.gz
if [ -f "input.tar.gz" ]; then
  echo "input.tar.gz already exists."
else
  echo "Downloading input.tar.gz"
  wget https://github.com/dafoam/files/releases/download/v1.0.0/input.tar.gz --no-check-certificate
fi

mpirun --oversubscribe -np 4 coverage run runTests_DALaplacianFoam.py